version: '3.3'

services:

  srv:
    image: ${DOCKER_USERNAME}/onec-server:${ONEC_VERSION}
    hostname: srv
    ports:
      - "1540-1541:1540-1541"
      - "1560:1560"
    volumes:
      - srv_data:/home/usr1cv8/.1cv8
      - srv_log:/var/log/1C
    networks:
      - back_net

  db:
    image: rsyuzyov/docker-postgresql-pro-1c:${ONEC_PG_VERSION}
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql
    networks:
      back_net:
        aliases:
          - db

  repo:
    image: ${DOCKER_USERNAME}/onec-crs:${ONEC_VERSION}
    ports:
      - "${CRS_PORT}:1542"
    volumes:
      - repo_data:/home/usr1cv8/.1cv8
    networks:
      - back_net

  ras:
    image: ${DOCKER_USERNAME}/onec-server:${ONEC_VERSION}
    entrypoint: /opt/1C/v8.3/x86_64/ras
    command: "cluster srv:1540"
    ports:
      - "${RAS_PORT}:1545"
    networks:
      - back_net

  client:
    image: ${DOCKER_USERNAME}/onec-client-vnc:${ONEC_VERSION}
    ports:
      - "5900:5900"
    volumes:
      - client_data:/home/usr1cv8/.1cv8
      - ${PWD}/nethasp.ini:/opt/1C/v8.3/x86_64/conf/nethasp.ini
    networks:
      - back_net

volumes:
  srv_data: {}
  srv_log: {}
  db_data: {}
  repo_data: {}
  client_data: {}

networks:
  back_net: {}
